### ISSUE TITLE
Missing amd64 in Release file

### ISSUE THREAD

**Issue by frli4797** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#14]
Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/erasmus-plex/dists/jessie/Release Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file) E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ryecoaaron** [comment]
There is an announcement and many other threads posted in the forum regarding this.

**Comment by ryecoaaron** [comment]
Should be fixed now.
