### ISSUE TITLE
i have a big proplem in my plex 

### ISSUE THREAD

**Issue by 1-2-3-ramus** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#15]
I have nas 520 (zyxel) with armhf....
plex is not to starting, why? see log

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; systemctl disable 'plexmediaserver' 2>&1' with exit code '1': Synchronizing state for plexmediaserver.service with sysvinit using update-rc.d... Executing /usr/sbin/update-rc.d plexmediaserver defaults insserv: warning: current start runlevel(s) (empty) of script `plexmediaserver' overrides LSB defaults (2 3 4 5). insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `plexmediaserver' overrides LSB defaults (0 1 6). Executing /usr/sbin/update-rc.d plexmediaserver disable insserv: warning: current start runlevel(s) (empty) of script `plexmediaserver' overrides LSB defaults (2 3 4 5). insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `plexmediaserver' overrides LSB defaults (0 1 6). Failed to execute operation: Die Wartezeit f?r die Verbindung ist abgelaufen

Fehler #0:
exception 'OMV\ExecException' with message 'Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; systemctl disable 'plexmediaserver' 2>&1' with exit code '1': Synchronizing state for plexmediaserver.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d plexmediaserver defaults
insserv: warning: current start runlevel(s) (empty) of script `plexmediaserver' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `plexmediaserver' overrides LSB defaults (0 1 6).
Executing /usr/sbin/update-rc.d plexmediaserver disable
insserv: warning: current start runlevel(s) (empty) of script `plexmediaserver' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `plexmediaserver' overrides LSB defaults (0 1 6).
Failed to execute operation: Die Wartezeit f?r die Verbindung ist abgelaufen' in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/php/openmediavault/system/systemctl.inc(86): OMV\System\Process->execute(Array, 1)
#1 /usr/share/php/openmediavault/system/systemctl.inc(119): OMV\System\SystemCtl->exec('disable', NULL, false)
#2 /usr/share/openmediavault/engined/module/plexmediaserver.inc(52): OMV\System\SystemCtl->disable(true)
#3 /usr/share/openmediavault/engined/rpc/config.inc(152): OMVModulePlexMediaServer->stopService()
#4 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(150): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(528): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusti...', '/tmp/bgoutput9V...')
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(151): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#9 /usr/share/openmediavault/engined/rpc/config.inc(213): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#10 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#11 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#12 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#13 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#14 {main}

**Comment by ryecoaaron** [comment]
Lots of info missing and most of the info you posted doesn't help.  What version of OMV?  What version is the plugin?  What were you doing when this happened?  This really would be better to post in the forum where many more people will see it/comment.

**Comment by 1-2-3-ramus** [comment]
i have the version omv 3.94 
i have upgrade the version plexmediaserver and is not to work the plex.... see log in the first post.

have you a chance this bug to fix?

**Comment by 1-2-3-ramus** [comment]
can you this bug fix?

**Comment by 1-2-3-ramus** [comment]
can you this bug today fix? yes or not?

**Comment by ryecoaaron** [comment]
No and that is why I said you should post on the forum.  There are many more people who could help there.

**Comment by 1-2-3-ramus** [comment]
okay, this bug is comming from update my plexmediaserver

**Comment by 1-2-3-ramus** [comment]
is software problem, my is now work :-) new installed is now okay :-)

**Comment by 1-2-3-ramus** [comment]
you can the ticket closed, please :-) is now working :-)
