### ISSUE TITLE
PlexPy fails to start due to missing plexpy user

### ISSUE THREAD

**Issue by u1735067** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#16]
Commit https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver/commit/96c0ae580408aa0fcc8c8a28c325774790904361 migrate the init script to the systemd unit, but it introduces an issue: the requested used in the unit is not existing.

`grep plexpy /etc/passwd` returns nothings but https://github.com/JonnyWong16/plexpy/blob/master/init-scripts/init.systemd require it.

This leads to
```
root@omv3:/opt/plexpy# systemctl status plexpy
● plexpy.service - PlexPy - Stats for Plex Media Server usage
   Loaded: loaded (/lib/systemd/system/plexpy.service; enabled)
   Active: failed (Result: exit-code) since Fri 2018-02-02 18:45:19 CET; 5s ago
  Process: 13465 ExecStart=/opt/plexpy/PlexPy.py --quiet --daemon --nolaunch --config /opt/plexpy/config.ini --datadir /opt/plexpy (code=exited, status=217/USER)

Feb 02 18:45:19 omv3 systemd[1]: Starting PlexPy - Stats for Plex Media Server usage...
Feb 02 18:45:19 omv3 systemd[13465]: Failed at step USER spawning /opt/plexpy/PlexPy.py: No such process
Feb 02 18:45:19 omv3 systemd[1]: plexpy.service: control process exited, code=exited status=217
Feb 02 18:45:19 omv3 systemd[1]: Failed to start PlexPy - Stats for Plex Media Server usage.
Feb 02 18:45:19 omv3 systemd[1]: Unit plexpy.service entered failed state.
```

**Comment by u1735067** [comment]
I have 3 solution: 

* [Solution 1](https://github.com/Alex131089/openmediavault-plexmediaserver/tree/Alex131089-systemd-fix-1) is the simpler I think, it will set the port in the `config.ini` file directly, but the application can modify it directly.
* [Solution 2](https://github.com/Alex131089/openmediavault-plexmediaserver/tree/Alex131089-systemd-fix-2) is the cleaner I think, it let the application handle the listening port as there's an option in the app (so there's no point to manage it for the app, as for Plex) ; the pyport option is removed, a documentation is added.
* [Solution 3](https://github.com/Alex131089/openmediavault-plexmediaserver/tree/Alex131089-systemd-fix-3) tries to keep the current system, by hacking the systemd unit file ; I don't like it, but it should work. It keeps plexpy running as the same user as plex (which I don't like either).

I'll make a PR with solution 2.

**Comment by henkall** [comment]
You should probably look into renaming from plexpy to tautulli and changing the git:
https://github.com/Tautulli/Tautulli.git

**Comment by u1735067** [comment]
Well, since nobody looked into the issue nor the PR, I'm not sure that's worth it for now (and github seems to redirect the project, at least for now).

**Comment by ryecoaaron** [comment]
I did look at the PR but I have no way to test it and I really want people to use docker instead of the plugin.  I've said this in the forum many times.  I'll accept the PR if you add the name change to the PR.

**Comment by u1735067** [comment]
Can you elaborate about docker? Do you have a (forum?) link eventually?
If an user don't follow the forums like me, how should we know?
I may change the name when I have time, so maybe not in a short delay.

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php/Thread/19553-OMV-Docker-plugin-media-server-Plex-PlexPy-Ombi-Libresonic-NZBGet-ruTorrent-Sona/
https://forum.openmediavault.org/index.php/Thread/22638-How-to-Install-Plex-Media-Server-in-a-docker-Video/
https://forum.openmediavault.org/index.php/Thread/19998-OMV-Setup-Videos/
Not much I can do if you don't follow the forum.  That is where I interact with OMV users.
