### ISSUE TITLE
Unable to open nested browsing contents

### ISSUE THREAD

**Issue by f5Qz** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#18]
From: https://bugtracker.openmediavault.org/view.php?id=1886

Unable to open the Plex iframe. This is when connected through OpenVPN, but I remember this also happens when connect on local LAN. I get the following error message in Chrome (63.0.3239.132):

```
ext-all.js:22

Refused to frame 'http://10.8.0.1:32400/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
https://developer.chrome.com/apps/contentSecurityPolicy

**Comment by ryecoaaron** [comment]
As I mentioned in your issue about the shellinabox plugin, there isn't much the plugin can do to fix this. This is an nginx and OMV security setting. The best solution is to open it in a new tab and not use iframes.

**Comment by f5Qz** [comment]
So why not remove the tab from plugin? It doesnt work... 

![openmediavault control panel odroidxu4](https://user-images.githubusercontent.com/35962391/35919342-139d5e72-0c15-11e8-96b7-bfb8e82c044b.png)

**Comment by ryecoaaron** [comment]
I am busy and this is not one of the plugins I want to maintain.  Feel free to submit a pull request removing it.
