### ISSUE TITLE
Plex not installing on openmediavault at all..

### ISSUE THREAD

**Issue by tripnarkey** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#2]
i have done a full reinstall of ovm wipe my ssd and even tried a new drive the last few weeks plex was work fine weeks ago?? but now nothing  i Love openmediavault been using over a year now .. 

Thank you for your time 

Dan..

**Comment by ryecoaaron** [comment]
This would be easier to solve on the forum - http://forums.openmediavault.org/
