### ISSUE TITLE
Plex Updates are quite behind

### ISSUE THREAD

**Issue by Samuel12321** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#21]

**Comment by ryecoaaron** [comment]
Only armhf is behind since i386 and amd64 use the official plex repo.  That said, I want to get rid of the plugin (won't be in OMV 5.x+) in favor of docker.

**Comment by Samuel12321** [comment]
wont this reduce performance due to emulation?

**Comment by ryecoaaron** [comment]
docker isn't emulation.  It uses the host's kernel in a container.  So, you will never notice any overhead.

**Comment by Samuel12321** [comment]
ok, thanks for clarifying that
