### ISSUE TITLE
404 on .deb file in Installer

### ISSUE THREAD

**Issue by tioulSidar** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#24]
Please update link to plex.tv.
Here the URL for x64 .deb file : 
https://downloads.plex.tv/plex-media-server-new/1.15.3.876-ad6e39743/debian/plexmediaserver_1.15.3.876-ad6e39743_amd64.deb

**Comment by ryecoaaron** [comment]
Nope.  Please start using docker - https://forum.openmediavault.org/index.php/Thread/23005-Installation-and-Setup-Videos-Begining-Intermediate-and-Advanced/?postID=175864#post175864

The plugin is only in the repo for legacy reasons.  I haven't updated the arm packages in forever.
