### ISSUE TITLE
can't find plexmediaserver plugin in omv

### ISSUE THREAD

**Issue by sylvainlap** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#4]
Hi,

I installed OpenMediaVault 2.x from the raspberry image.

I enabled OMV-Extras.org repos (All) in the plugin section, so I have a lot of plugins (downloaders, transmissionbt, mumble...), but I can't find plexmediaserver plugin... How can I get this plugin ?

**Comment by ryecoaaron** [comment]
It should be although the plex packager stopped updating the package for Wheezy (OMV 2.x).  What is the output of:  apt-cache policy openmediavault-plexmediaserver

**Comment by sylvainlap** [comment]
```
root@raspberrypi:~# apt-cache policy openmediavault-plexmediaserver
N: Unable to locate package openmediavault-plexmediaserver
```

**Comment by ryecoaaron** [comment]
What is the output of:  cat /etc/apt/sources.list.d/omv-extras-org-stoneburner.list

**Comment by sylvainlap** [comment]
```
root@raspberrypi:~# cat /etc/apt/sources.list.d/omv-extras-org-stoneburner.list
# Regular omv-extras.org repo
deb http://packages.omv-extras.org/debian/ stoneburner main
# Testing omv-extras.org repo
deb http://packages.omv-extras.org/debian/ stoneburner-testing main
```

**Comment by ryecoaaron** [comment]
You need to enable the plex repo in omv-extras.  You only have the main and testing repos enabled.
