### ISSUE TITLE
wrong database location with plexmediaserver plugin in OMV 3.x

### ISSUE THREAD

**Issue by belierzz** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#5]
setting up plexmediaserver via webgui with /dev/sdb3 as own partition for
database location on SSD works well. Anyway, plexmediaserver folder is still
created additionally in /var/lib/ and filled accordingly. 

can be easily reproduced when setting up plex in fresh OMV 3.x installation. 
knowing OMV based on Jessie is still beta, just want to contribute to this
fantastic project with my moderate possibilities. feel free to move or delete
if this post is nok. thanks.

**Comment by ryecoaaron** [comment]
We will probably have to go back to using the ninthgate packages since it seems the regular ubuntu package we are using now ignores the plex user's home directory setting.  I will have to look at the systemd unit file in the package to see if there is a workaround.

**Comment by ryecoaaron** [comment]
This thread is helpful:  https://forums.plex.tv/discussion/70931/is-it-possible-to-move-server-metadata-to-another-location

**Comment by tekkbebe** [comment]
/etc/systemd/system/plexmediaserver.service
/media/uuid/plexmediaserver

Environment="PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/var/lib/plexmediaserver/Library/Application Support"

sed search for /var/lib/plexmediaserver
replace with variable already there ${PLEX_HOME}

systemctl daemon-reload

This is not hard to fix!!!!  Working on it.

**Comment by tekkbebe** [comment]
The question is what happens on upgrade.  I will test that now.
I have to wait a bit for some metadata to finish.

**Comment by tekkbebe** [comment]
Fix done and tested but not with upgrade... bash script I tested:
 #!/bin/bash

DEFAULT_HOME="/var/lib/plexmediaserver"
PLEX_HOME="$(getent passwd plex | cut -d: -f6)"

sed -i "s#${DEFAULT_HOME}#${PLEX_HOME}#" /scratch/plexmediaserver.service

Just need to check if it will hold post upgrade.

**Comment by tekkbebe** [comment]
Tested post upgrade....  RESOLVED!!!!  I will put new code in master branch.
Only had to add this line in the right place... LOL
sed -i "s#${PLEX_HOME}#${DB_FOLDER}#" /etc/systemd/system/plexmediaserver.service

**Comment by tekkbebe** [comment]
Version upgrade to changelog done  Aaron.  I also fixed some linkedfield issues.

**Comment by lilingang** [comment]
Why not delete user when uninstall the plug ?
There will be a problem when you reinstall because the user environment variables exist

HOME=/media/889f8f27-ac20-4f2d-bc33-94fc584daef8/plexmediaserver

Error Message:
stat: cannot stat '/media/889f8f27-ac20-4f2d-bc33-94fc584daef8/plexmediaserver/Library': No such file or directory

**Comment by ryecoaaron** [comment]
The plugin doesn't create the user.  Therefore, I think it should be the responsibility of the plex package to delete the user.  Someone may want to keep plex installed and not the plugin.

**Comment by belierzz** [comment]
Will there be an update on bintray for OMV 3.x in the short term? 
Thanks in advance!

**Comment by ryecoaaron** [comment]
No because OMV 3.x is going to make a huge change soon (another reason why no one should be using it yet).  So, the plugin will be changing a lot as well.
