### ISSUE TITLE
Plex Media Server needing update to at least 0.9.15

### ISSUE THREAD

**Issue by FiifiB** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#6]
Hi i was wandering if you could update the plex media server from omv extras repo so that i could use a version later than 0.9.12.4. Would really like to use it on my iPad. Currently have OMV 2.2 running on an armv7 device that powerful enough to use the latest version of plex media server. Any help on this will be much appreciated.
Also may i ask when a version of OMV 3.x will be available for arm devices
Thanks

**Comment by ryecoaaron** [comment]
The dev creating the package stopped creating them for Wheezy (OMV 2.x).  So, you will have to wait until OMV 3.x.

There is no release date but it is being worked on.
