### ISSUE TITLE
apt error weak key

### ISSUE THREAD

**Issue by f-vt** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#7]
New Apt updates (from testing) makes mandatory to use sha256 in release and packages files :

https://wiki.debian.org/Teams/Apt/Sha1Removal 

error from apt-get update :
W: http://packages.openmediavault.org/public/dists/erasmus/InRelease: Signature by key 0F6BCC17C26BFADC27F221007E7A6C592EF35D13 uses weak digest algorithm (S
HA1)

**Comment by ryecoaaron** [comment]
That is a problem with the developer of OMV itself (Volker) signing key.  File on bugtracker - http://bugtracker.openmediavault.org/

**Comment by f-vt** [comment]
Oh sorry,

yes his key is also weak, i've made a mistake in my copy/paste ; that's the error message for this repo :

W: http://dh2k.omv-extras.org/debian/dists/plex-jessie-mirror/InRelease: Signature by key A4734E097C93F0DB37BD00A57B9C5D187860A018 uses weak digest algorithm (SHA1)

Le 5 juil. 2016 ? 17:27, Aaron Murray <notifications@github.com<mailto:notifications@github.com>> a ?crit :

That is a problem with the developer of OMV itself (Volker) signing key. File on bugtracker - http://bugtracker.openmediavault.org/

##
